service: aws-ses-serverless-example
app: aws-ses-serverless-example
org: <YOUR_ORG>

custom:
    defaultRegion: eu-central-1
    defaultStage: dev

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}

  endpointType: regional # Optional endpoint configuration for API Gateway REST API. Default is Edge.
  apiKeys:
    - name: shiftsApiKeys
      value: ${opt:myApiKey}

  usagePlan:
    quota:
      limit: 1000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

  iamRoleStatements:
    - Effect: "Allow"
      Action: "ses:SendEmail"
      Resource: { "Fn::Join" : ["", ["arn:aws:ses:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":identity/*" ] ]  }

plugins:
  - serverless-webpack

functions:
  sendMail:
    handler: handler.sendMail
    description: Send email using SES service.
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: sendMail
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
